### ISSUE TITLE
Unable to use the site

### ISSUE THREAD

**Issue by Hunter16g** [axmccx/proxynexus#1]
Thanks for the site, it looks great. The decklist, set and card list buttons don't do anything for me though. I'm using Firefox 60.5.1esr (64 bits)

**Comment by axmccx** [comment]
Thanks for pointing this out, gonna get a fix out asap.

**Comment by axmccx** [comment]
I've just pushed a fix. I was using some regular expressions that were only supported in Chrome. Although the site should work now in other browsers, I see that the "Download PDF" function isn't functional in browsers other than Chrome, because it's effectively printing the page. I recommend using Chrome until I move the PDF generation process to the server end.
